version: '3.9'
services:
  readmeUsersMongo:
    image: mongo:4.4
    restart: always
    container_name: readmeUsersMongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - 27017:27017

    volumes:
      - readmeMongoUsers:/data/db

    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:${MONGO_PORT}/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  readmeUserMongoUi:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readmeUserMongoUi
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readmeUsersMongo:${MONGO_PORT}/

volumes:
  readmeMongoUsers:
